name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.name "sfuentes"
          git config --global user.email "dev@sfuentes.cl"

      - name: Add GitLab remote
        run: git remote add gitlab https://Ifaen:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Ifaen/NixOS.git

      - name: Force push to GitLab
        run: git push --force gitlab main
